steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - run
  - deploy
  - $_SERVICE_NAME
  - --image
  - gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA
image:
  - gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA
options:
  logging: CLOUD_LOGGING_ONLY
