steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - $_SERVICE_NAME
  - --region=asia-northeast1
  - --trigger-http
  - --gen2
options:
  logging: CLOUD_LOGGING_ONLY
